// Request mock data removed — requests are stored in the database now.
const mockDonations = [
  {
    id: 'don1',
    donorId: 'donor1',
    donorName: 'Akshaya Patra Foundation',
    donorType: 'organization',
    pickupAddress: 'Akshaya Patra Kitchen, Koramangala',
    district: 'Bangalore',
    state: 'Karnataka',
    category: 'food-nutrition',
    specificResource: 'Cooked Meals',
    quantity: 1000,
    unit: 'meals',
    condition: 'consumable',
    availableUntil: '2024-02-09T20:00:00',
    canDeliver: true,
    canPickup: true,
    deliveryRadius: 100,
    status: 'available',
    createdAt: '2024-02-08T07:00:00',
  },
  {
    id: 'don2',
    donorId: 'donor2',
    donorName: 'TCS CSR Initiative',
    donorType: 'organization',
    pickupAddress: 'TCS Campus, Siruseri',
    district: 'Chennai',
    state: 'Tamil Nadu',
    category: 'medical-healthcare',
    specificResource: 'First Aid Kits',
    quantity: 100,
    unit: 'units',
    condition: 'new',
    availableUntil: '2024-02-15T18:00:00',
    canDeliver: true,
    canPickup: true,
    deliveryRadius: 50,
    status: 'available',
    createdAt: '2024-02-08T09:00:00',
  },
  {
    id: 'don3',
    donorId: 'donor3',
    donorName: 'Sundar Rajan',
    donorType: 'individual',
    pickupAddress: '56, MG Road',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    category: 'shelter-clothing',
    specificResource: 'Blankets',
    quantity: 50,
    unit: 'pieces',
    condition: 'new',
    availableUntil: '2024-02-20T18:00:00',
    canDeliver: false,
    canPickup: true,
    deliveryRadius: 0,
    status: 'available',
    createdAt: '2024-02-08T11:00:00',
  },
];

const mockOrganizations = [
  {
    id: 'org1',
    name: 'Red Cross India - Chennai Chapter',
    type: 'ngo',
    specialization: 'Medical Aid & Emergency Response',
    description: 'Leading humanitarian organization providing emergency assistance, disaster relief, and health services.',
    address: 'Red Cross Building, Anna Salai, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    contactEmail: 'chennai@redcross.org',
    contactPhone: '+91 44 2852 4567',
    isVerified: true,
    impactMetrics: {
      peopleHelped: 50000,
      resourcesDonated: 15000,
      requestsFulfilled: 1200,
    },
    createdAt: '2020-01-01',
  },
  {
    id: 'org2',
    name: 'Akshaya Patra Foundation',
    type: 'ngo',
    specialization: 'Food Distribution',
    description: "Running the world's largest NGO-run school lunch programme. Extends support during disasters.",
    address: 'Akshaya Patra Campus, Koramangala, Bangalore',
    district: 'Bangalore',
    state: 'Karnataka',
    contactEmail: 'relief@akshayapatra.org',
    contactPhone: '+91 80 3014 3400',
    isVerified: true,
    impactMetrics: {
      peopleHelped: 200000,
      resourcesDonated: 500000,
      requestsFulfilled: 3500,
    },
    createdAt: '2019-06-15',
  },
];

const mockPOCs = [
  {
    id: 'poc1',
    name: 'Dr. Karthik Subramanian',
    designation: 'District Disaster Management Officer',
    district: 'Chennai',
    state: 'Tamil Nadu',
    email: 'karthik.s@tn.gov.in',
    phone: '+91 44 2567 1234',
    officeHours: '9:00 AM - 6:00 PM',
    isAvailable: true,
  },
  {
    id: 'poc2',
    name: 'Mrs. Revathi Krishnamurthy',
    designation: 'Additional District Collector',
    district: 'Cuddalore',
    state: 'Tamil Nadu',
    email: 'revathi.k@tn.gov.in',
    phone: '+91 4142 234 567',
    officeHours: '10:00 AM - 5:00 PM',
    isAvailable: true,
  },
];

module.exports = {
  mockDonations,
  mockOrganizations,
  mockPOCs,
};
